services:
  - type: web
    name: golf-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: INSTANCE_DIR
        value: /var/data/instance
      - key: DATABASE_URL
        value: /var/data/instance/golf.db
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1