services:
  - type: web
    name: golf-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p /opt/render/project/src/data
      chmod 777 /opt/render/project/src/data
      # Copy initial data files if they don't exist
      cp -n data/*.json /opt/render/project/src/data/ 2>/dev/null || true
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_APP
        value: app.py
      - key: DATA_DIR
        value: /opt/render/project/src/data
