services:
  - type: web
    name: golf-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p instance
      chmod 777 instance
    startCommand: gunicorn "app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: RENDER
        value: "true"
      - key: INSTANCE_DIR
        value: /opt/render/project/src/instance